version: '3.8'

services:
  repositorystatistics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repositorystatistics
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=repository_statistics
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=repository_statistics
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    name: repository-statistics-network

volumes:
  mongodb_data:
    name: mongodb_data